---
title: "Data_import"
author: "Clement Mugenzi"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl) # read in an excel file 
library(skimr)
library(haven)
```

# Loading the dataset

```{r}
## Reads in a dataset
## Absolute path and relative path - prefer relative path
wrang_df <- read_csv(file = "data_import_examples/FAS_litters.csv",
                     col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
wrang_df <- janitor::clean_names(wrang_df) # cleaning names and 
# also use janitor::.. only if the package has not been loaded.

wrang_df = janitor::clean_names(wrang_df)
```


```{r}
# loading in the pups data
pups_df <- read_csv("data_import_examples/FAS_pups.csv")
pups_df <- janitor::clean_names(pups_df) # dont view dataset in rmarkdown

```

run this class(pull(pups_df, )) to see what kind of variable you have.

## Read in excel file...

```{r}
mlb11_data = read_excel(path = "data_import_examples/mlb11.xlsx",
                        range = "A1:D7") 

# range just reads a subset of the dataset
view(mlb11_data)
```

## Read in SAS

```{r}
pulse_data = read_sas("data_import_examples/public_pulse_data.sas7bdat")
view(pulse_data)
# So why read_csv and not read.csv? Because read_csv imports datasets as a tibble, not a dataframe whereas read.csv imports data as dataframes.
```


# Data Manipulation


```{r}
select(wrang_df, group, litter_number)
select(wrang_df, group, litter_number, gd0_weight)
select(wrang_df, group, litter_number, gd0_weight, starts_with("pups"))
select(wrang_df, litter_number, group, gd0_weight)
select(wrang_df, litter_number, group, everything())
select(wrang_df, litter_number, -group)
select(wrang_df, litter_number, gd0_weight:pups_born_alive) # define the new dataframe by calling it another name.
select(wrang_df, GROUP = group, litter_number) # rename a variable through select function.
rename(wrang_df, GROUP = group, litter.number = litter_number)
```


## Filtering

```{r}
filter(wrang_df, group == "Mod8") # == differentiate between assigning a new parameter and equalizing 
filter(wrang_df, gd_of_birth == 20)
filter(wrang_df, gd_of_birth < 20)
filter(wrang_df, pups_born_alive < 6, group == "Con7")
filter(wrang_df, group == "Con7" | group == "Mod8") # Using OR
filter(wrang_df, group %in% c("Con7", "Mod8")) # this and line 90 do the same thing
filter(wrang_df, pups_born_alive >= 4, pups_born_alive <= 6)
# Don't do this:
# filter(wrang_df, is.na(gd0_weight))

drop_na(wrang_df, gd0_weight, gd18_weight) # Getting rid of missing values

```

## Mutate

```{r}
mutate(wrang_df, wt_gain = gd18_weight - gd0_weight,
       group = str_to_lower(group))
```

## Arrange (same as sort)

```{r}
arrange(wrang_df, pups_born_alive)

arrange(wrang_df, desc(pups_born_alive))

arrange(wrang_df, pups_born_alive, gd0_weight) # goes in a hierarchy order.

```


## Pipe

let us create a collection of commands...

```{r}
wrang_df = 
  read_csv("data_manipulation_examples/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>%
  drop_na(gd0_weight)
wrang_df
```


```{r}
wrang_df = 
  read_csv("data_manipulation_examples/FAS_litters.csv") %>%
  janitor::clean_names(dat = .) %>%
  select(.data = ., -pups_survive)
wrang_df
# Do not worry about this right now.
```



# Tidying Data

## Wide to long

```{r}
library(tidyr)
pulse_data = 
  haven::read_sas("data_Tidy_examples /public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>% 
  mutate(
    visit = recode(visit, "bl" = "00m")
  )
  

```


## Separate in litters

```{r}
wrang_df = 
  read_csv("data_Tidy_examples /FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  separate(col = group, into = c("dose", "day_of_tx"), 3)
view(wrang_df)
```


## Using pivot_wider


```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)
# longer to wider
pivot_wider(
  analysis_result,
  names_from = time,
  values_from = mean,
)
```


## Binding Rows


```{r}
fellowship_ring = 
  readxl::read_excel("data_Tidy_examples /LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship")

two_towers = 
  readxl::read_excel("data_Tidy_examples /LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("data_Tidy_examples /LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

lotr_data = 
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  ) %>% 
  select(movie, race, sex, words)
```

## Joining datasets

```{r}
pup_data = 
  read_csv("data_Tidy_examples /FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("data_Tidy_examples /FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))

fas_data = 
  left_join(pup_data, litter_data, by = "litter_number")
fas_data

# Try to join these

fas_data = 
  left_join(pup_data, litter_data, by = "litter_number")
```























